[build]
  publish = ""
  command = "npm run"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/avif"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"